name: Go CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Go CI Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Verify Formatting
        run: |
          echo "Checking gofmt..."
          fmt_result=$(gofmt -l .)
          if [ -n "$fmt_result" ]; then
            echo "The following files need formatting:"
            echo "$fmt_result"
            exit 1
          fi

      - name: Run tests
        run: go test ./... -v
